var variables = {
    x: 270,
    y: 350,
    counterUsers: 1,
    radian: 0,
    keyUp: [38],
    r: 2,
    out: null,
    in: null,
    ctx: null,
    img: null,
    finish: null,
    counter: 5,
    helper1: true,
    helper2: true,
    helper3: true,
    helper4: true,
    users: [
        { id: 1, name: 'Gracz 1', key: "ArrowUp", color: "rgb(92, 92, 253)", active: "yes", x: 270, y: 320, radian: 0, img: null, press: false, up: false, radian: 0, c: null, lap: 2 },
        { id: 2, name: 'Gracz 2', key: "ArrowRight", color: "rgb(248, 206, 16)", active: "no", x: 270, y: 340, radian: 0, img: null, press: false, up: false, radian: 0, c: null, lap: 2 },
        { id: 3, name: 'Gracz 3', key: "ArrowDown", color: "rgb(199, 69, 90)", active: "no", x: 270, y: 380, radian: 0, img: null, press: false, up: false, radian: 0, c: null, lap: 2 },
        { id: 4, name: 'Gracz 4', key: "ArrowLeft", color: "rgb(39, 156, 39)", active: "no", x: 270, y: 420, radian: 0, img: null, press: false, up: false, radian: 0, c: null, lap: 2 },
    ],
}

